In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# 単純なアレイを用意します。

arr1 = np.arange(9).reshape((3, 3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# 2つのアレイを列方向（axis=1）に連結します

np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# 行方向（axis=0）に

np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# pandas.Seriesでやってみます。

ser1 = Series([0, 1, 2], index=['T', 'U', 'V'])
ser2 = Series([3, 4], index=['X', 'Y'])

# concatで、デフォルトは axis=0
pd.concat([ser1, ser2, ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [7]:
# 列方向に連結すると、DataFrameが出来ます。

pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [8]:
# 階層的なindexを付けてSeriesを連結することもできます。

pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [9]:
# 列方向に連結すると、列の名前になります。

pd.concat([ser1, ser2], axis=1, keys=['cat1', 'cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [11]:
# DataFrameでも同じ事ができます。

dframe1 = DataFrame(np.random.randn(4, 3),
                    columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3),
                    columns=['Y', 'Q', 'X'])

In [12]:
dframe1

X         Y         Z
0  2.230077  0.565566  0.147030
1 -0.096306 -1.161655 -0.504702
2 -1.628548  0.123159  0.339923
3  1.916046  0.114036  0.405891

In [13]:
dframe2

Y         Q         X
0 -0.883876 -0.804876  1.586765
1  0.472801  0.543786  0.164667
2  0.139137  0.699790 -0.304232

In [14]:
# DataFrameを連結します。

pd.concat([dframe1, dframe2])

X         Y         Z         Q
0  2.230077  0.565566  0.147030       NaN
1 -0.096306 -1.161655 -0.504702       NaN
2 -1.628548  0.123159  0.339923       NaN
3  1.916046  0.114036  0.405891       NaN
0  1.586765 -0.883876       NaN -0.804876
1  0.164667  0.472801       NaN  0.543786
2 -0.304232  0.139137       NaN  0.699790

In [15]:
# もとのindexを無視することもできます。

pd.concat([dframe1, dframe2], ignore_index=True)

X         Y         Z         Q
0  2.230077  0.565566  0.147030       NaN
1 -0.096306 -1.161655 -0.504702       NaN
2 -1.628548  0.123159  0.339923       NaN
3  1.916046  0.114036  0.405891       NaN
4  1.586765 -0.883876       NaN -0.804876
5  0.164667  0.472801       NaN  0.543786
6 -0.304232  0.139137       NaN  0.699790

In [16]:
# 公式ドキュメントはこちらです。
url = 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html'