In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 平方根を計算する

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
# 自然対数の底ｅの累乗

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
# 標準正規分布に従う乱数

A = np.random.randn(10)
A

array([ 0.43973387,  1.08151535, -0.68623752,  1.15338374, -0.23909561,
       -0.38199545, -0.00426117, -0.89982338, -0.56311295, -0.01829235])

In [6]:
# 別のアレイも用意（乱数の発生方法を変更）

rng = np.random.default_rng()
B = rng.standard_normal(10)
B

array([-0.13603882,  1.51970573,  0.16515461,  1.05424748, -1.67784604,
       -0.81958586, -1.6221169 , -0.51203105, -0.30768532,  1.34761338])

In [7]:
# 2つのアレイを足す

np.add(A, B)

array([ 0.30369505,  2.60122109, -0.5210829 ,  2.20763122, -1.91694166,
       -1.20158131, -1.62637807, -1.41185443, -0.87079827,  1.32932103])

In [8]:
# 各要素の大きいほうを返す

np.maximum(A, B)

array([ 0.43973387,  1.51970573,  0.16515461,  1.15338374, -0.23909561,
       -0.38199545, -0.00426117, -0.51203105, -0.30768532,  1.34761338])

In [ ]:
# この他の演算子に関しては、numpyのドキュメントに詳しい情報があります。

website = "https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)