In [3]:
# Numpyのアレイを利用
import numpy as np

# Pythonのリスト型から変換して作ることができる。
my_list1 = [1, 2, 3, 4]

my_array1 = np.array(my_list1)

In [4]:
# アレイを表示する
my_array1

array([1, 2, 3, 4])

In [5]:
# 別のアレイを作って
my_list2 = [11, 22, 33, 44]

# リストのリストを作成
my_lists = [my_list1, my_list2]

# これを使って、多次元のアレイを作れる
my_array2 = np.array(my_lists)

my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [6]:
# アレイのサイズを調べる
my_array2.shape

(2, 4)

In [7]:
# アレイのデータ型を調べる
my_array2.dtype

dtype('int64')

In [8]:
# 特別なアレイを作る

#すべての要素が０
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
my_zeros_array = np.zeros(5)

In [10]:
my_zeros_array.dtype

dtype('float64')

In [11]:
#すべての要素が1
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# 空っぽのアレイ

np.empty(5)
np.empty((3, 4))

array([[-3.10503618e+231, -1.49457561e-154,  2.96439388e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  2.42336543e-057,  5.44928172e-090,
         2.70237009e-056],
       [ 5.41762006e-067,  2.79187847e+179,  3.99910963e+252,
         8.34402697e-309]])

In [13]:
#単位行列I（dentity array）
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# arange関数
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])