In [1]:
import numpy as np

In [12]:
# 簡単なアレイを作る

arr = np.arange(5)

In [13]:
# バイナリデータとして保存 (拡張子は .npy)

np.save('my_array', arr)

In [4]:
# アレイを少し変更

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 保存したアレイを読み込む

arr1 = np.load('my_array.npy')
arr1

array([0, 1, 2, 3, 4])

In [6]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 複数のアレイをzip形式で保存

np.savez('ziparrays.npz', x=arr1, y=arr2)

In [8]:
# ディスクから読み込む

archive_array = np.load('ziparrays.npz')
archive_array['x']

array([0, 1, 2, 3, 4])

In [9]:
# テキストファイルとしても保存できます。

arr = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('my_test_text.txt', arr, delimiter=',')

In [10]:
!cat my_test_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00


In [11]:
arr = np.loadtxt('my_test_text.txt', delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])